language: ruby
install:
  - sudo apt-get install xvfb
  - rvm install 2.3.1 --default
  - gem install bundler
  - gem install cucumber
  - gem install capybara
  - gem install selenium-client
  - gem install selenium-webdriver

script:
  - DISPLAY=localhost:99 xvfb-run cucumber features/
